import express from 'express';
import { engine } from 'express-handlebars';
import { fileURLToPath } from 'node:url';
import { getHome } from './controllers/home.controller.js';
import servicesRouter from './routes/services.router.js';
import bookingsRouter from './routes/bookings.router.js';
import messagesRouter from './routes/messages.router.js';
import viewsRouter from './routes/views.router.js';
import { errorStatus } from './utils/errors.js';
const app = express();
app.engine('handlebars', engine());
app.set('view engine', 'handlebars');
app.set('views', fileURLToPath(new URL('./views', import.meta.url)));
app.use(express.json({ limit: '100kb' }));
app.use(express.static(fileURLToPath(new URL('../public', import.meta.url))));
app.get('/', getHome);
app.use('/api/services', servicesRouter);
app.use('/api/bookings', bookingsRouter);
app.use('/api/messages', messagesRouter);
app.use('/views', viewsRouter);
app.use((req, res) => res.status(404).json({ status: 'error', message: 'Ruta no encontrada' }));
app.use((error, req, res, next) => {
  const status = errorStatus(error);
  const message = status === 500 ? 'No se pudo completar la consulta.' : error.message;
  if (req.path.startsWith('/views')) return res.status(status).render('error', { title: 'Error', message });
  res.status(status).json({ status: 'error', message });
});
export default app;
